[build]
  command = "npm run build"
  publish = "frontend/build"

[build.environment]
  FUNCTIONS_SRC = "backend"
  FUNCTIONS_DIST = "functions"

[[redirects]]
  from = "/users/*"
  to = "/.netlify/functions/:splat"
  status = 200